package com.thw.shoppingcart.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.thw.shoppingcart.db.Category;
import com.thw.shoppingcart.db.Product;
import com.thw.shoppingcart.db.Cart;

import com.thw.shoppingcart.db.CategoryDao;
import com.thw.shoppingcart.db.ProductDao;
import com.thw.shoppingcart.db.CartDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig cartDaoConfig;

    private final CategoryDao categoryDao;
    private final ProductDao productDao;
    private final CartDao cartDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        cartDaoConfig = daoConfigMap.get(CartDao.class).clone();
        cartDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        cartDao = new CartDao(cartDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Product.class, productDao);
        registerDao(Cart.class, cartDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        cartDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public CartDao getCartDao() {
        return cartDao;
    }

}
